# Generated by Django 4.1 on 2022-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem_contact_orderitem_unique_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='model',
            field=models.CharField(blank=True, max_length=60, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Название'),
        ),
    ]
