# Generated by Django 4.1 on 2022-09-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_info',
        ),
    ]
